export const mockResponse = {
  moviesReducer: {
    page: 1,
    results: [
      {
        original_title: "Spider-Man: No Way Home",
        poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        title: "Spider-Man: No Way Home",
      },
      {
        id: 425909,
        poster_path: "/sg4xJaufDiQl7caFEskBtQXfD4x.jpg",
        video: false,
        vote_average: 7.2,
        overview:
          "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
        release_date: "2021-11-11",
        vote_count: 703,
        adult: false,
        backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
        title: "Ghostbusters: Afterlife",
        genre_ids: [35, 14, 12],
        original_title: "Ghostbusters: Afterlife",
        original_language: "en",
        popularity: 5128.218,
        media_type: "movie",
      },
      {
        original_language: "en",
        original_title: "Sing 2",
        poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
        video: false,
        id: 438695,
        overview:
          "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
        release_date: "2021-12-01",
        vote_count: 214,
        vote_average: 7.5,
        adult: false,
        backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
        title: "Sing 2",
        genre_ids: [16, 35, 10751, 10402],
        popularity: 6229.952,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/4NybrtAXRtJd2h83fOTPGftz3LI.jpg",
        genre_ids: [28, 12, 14, 878],
        vote_count: 1612,
        original_language: "en",
        original_title: "Eternals",
        poster_path: "/6AdXwFTRTAzggD2QUTt5B7JFGKL.jpg",
        vote_average: 7.1,
        video: false,
        id: 524434,
        title: "Eternals",
        overview:
          "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.",
        release_date: "2021-11-03",
        popularity: 1765.886,
        media_type: "movie",
      },
      {
        video: false,
        vote_average: 7.0,
        overview:
          "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
        release_date: "2021-12-16",
        adult: false,
        backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
        id: 624860,
        genre_ids: [878, 28, 12],
        vote_count: 1970,
        original_language: "en",
        original_title: "The Matrix Resurrections",
        poster_path: "/gZlZLxJMfnSeS60abFZMh1IvODQ.jpg",
        title: "The Matrix Resurrections",
        popularity: 5478.476,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/aj02AhFaRsAqtFtjbythaIwGvx4.jpg",
        genre_ids: [18],
        id: 727293,
        original_language: "en",
        original_title: "The Tender Bar",
        overview:
          "J.R. is a fatherless boy growing up in the glow of a bar where the bartender, his Uncle Charlie, is the sharpest and most colorful of an assortment of quirky and demonstrative father figures. As the boy’s determined mother struggles to provide her son with opportunities denied to her — and leave the dilapidated home of her outrageous if begrudgingly supportive father — J.R. begins to gamely, if not always gracefully, pursue his romantic and professional dreams, with one foot persistently placed in Uncle Charlie’s bar.",
        poster_path: "/m6Ej3F4tYTOHD26fvX1zN9bcEUg.jpg",
        release_date: "2021-12-17",
        title: "The Tender Bar",
        video: false,
        vote_average: 6.7,
        vote_count: 59,
        popularity: 56.721,
        media_type: "movie",
      },
      {
        poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
        video: false,
        vote_average: 7.8,
        overview:
          "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
        id: 568124,
        vote_count: 2464,
        adult: false,
        backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
        title: "Encanto",
        genre_ids: [16, 35, 10751, 14],
        release_date: "2021-11-24",
        original_language: "en",
        original_title: "Encanto",
        popularity: 7247.534,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/AmLpWYm9R3Ur2FLPgj5CH3wR8wp.jpg",
        genre_ids: [878, 53],
        id: 739413,
        original_language: "en",
        original_title: "Mother/Android",
        overview:
          "Georgia and her boyfriend Sam go on a treacherous journey to escape their country, which is caught in an unexpected war with artificial intelligence. Days away from the arrival of their first child, the couple must face No Man’s Land—a stronghold of the android uprising—in hopes of reaching safety before giving birth.",
        poster_path: "/rO3nV9d1wzHEWsC7xgwxotjZQpM.jpg",
        release_date: "2021-12-17",
        title: "Mother/Android",
        video: false,
        vote_average: 6.1,
        vote_count: 178,
        popularity: 119.512,
        media_type: "movie",
      },
      {
        original_language: "en",
        original_title: "Resident Evil: Welcome to Raccoon City",
        poster_path: "/7uRbWOXxpWDMtnsd2PF3clu65jc.jpg",
        video: false,
        vote_average: 6.0,
        id: 460458,
        release_date: "2021-11-24",
        vote_count: 780,
        title: "Resident Evil: Welcome to Raccoon City",
        adult: false,
        backdrop_path: "/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
        overview:
          "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
        genre_ids: [27, 28, 878],
        popularity: 6821.31,
        media_type: "movie",
      },
      {
        overview:
          "Two low-level astronomers must go on a giant media tour to warn humankind of an approaching comet that will destroy planet Earth.",
        release_date: "2021-12-07",
        adult: false,
        backdrop_path: "/nvxrQQspxmSblCYDtvDAbVFX8Jt.jpg",
        vote_count: 3336,
        genre_ids: [18, 35, 878],
        id: 646380,
        original_language: "en",
        original_title: "Don't Look Up",
        poster_path: "/th4E1yqsE8DGpAseLiUrI60Hf8V.jpg",
        title: "Don't Look Up",
        video: false,
        vote_average: 7.3,
        popularity: 1268.861,
        media_type: "movie",
      },
      {
        backdrop_path: "/8rft8A9nH43IReybFtYt21ezfMK.jpg",
        genre_ids: [99],
        original_language: "en",
        original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
        poster_path: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
        video: false,
        vote_average: 8.4,
        vote_count: 644,
        overview:
          "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
        id: 899082,
        title: "Harry Potter 20th Anniversary: Return to Hogwarts",
        release_date: "2022-01-01",
        adult: false,
        popularity: 1633.941,
        media_type: "movie",
      },
      {
        original_language: "en",
        original_title: "Venom: Let There Be Carnage",
        poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
        video: false,
        vote_average: 7.2,
        id: 580489,
        release_date: "2021-09-30",
        vote_count: 5693,
        title: "Venom: Let There Be Carnage",
        adult: false,
        backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
        overview:
          "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
        genre_ids: [878, 28, 12],
        popularity: 4192.169,
        media_type: "movie",
      },
      {
        genre_ids: [12, 28, 53],
        original_language: "en",
        original_title: "No Time to Die",
        id: 370172,
        title: "No Time to Die",
        video: false,
        vote_average: 7.5,
        overview:
          "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
        release_date: "2021-09-29",
        vote_count: 3087,
        adult: false,
        backdrop_path: "/r2GAjd4rNOHJh6i6Y0FntmYuPQW.jpg",
        poster_path: "/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
        popularity: 1063.867,
        media_type: "movie",
      },
      {
        genre_ids: [878, 12],
        vote_count: 5367,
        original_language: "en",
        original_title: "Dune",
        poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
        release_date: "2021-09-15",
        video: false,
        vote_average: 7.9,
        adult: false,
        backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
        title: "Dune",
        overview:
          "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
        id: 438631,
        popularity: 973.927,
        media_type: "movie",
      },
      {
        poster_path: "/s7nsixJ7SeJG2Pmd3W19EbfdRPe.jpg",
        video: false,
        vote_average: 6.6,
        id: 592695,
        overview:
          "20-year-old Bella Cherry leaves her small town in Sweden for Los Angeles with the aim to become the world's next big porn star but the road to her goal turns out to be bumpier than she imagined.",
        release_date: "2021-10-08",
        adult: false,
        backdrop_path: "/y0LhmaMYpFkIfrUlOpJYTVMH2eA.jpg",
        vote_count: 25,
        genre_ids: [18],
        title: "Pleasure",
        original_language: "en",
        original_title: "Pleasure",
        popularity: 30.813,
        media_type: "movie",
      },
      {
        id: 800410,
        original_language: "es",
        original_title: "El páramo",
        poster_path: "/l9gEXGQgJxbFFPy9NWPt4leKGDU.jpg",
        video: false,
        vote_average: 4.8,
        overview:
          "Lucía and her son live isolated from society in a flat place where there’s practically no life. The small family unit formed by mother and son hardly ever receives visitors, and their goal is to lead a quiet existence. At first they succeed, but the appearance of a mysterious, violent creature that starts stalking their small house will put the relationship that unites them to the test.",
        release_date: "2021-10-12",
        vote_count: 45,
        adult: false,
        backdrop_path: "/mhIPm0FhVX60n9sSlcWL436TFae.jpg",
        title: "The Wasteland",
        genre_ids: [18, 27, 53],
        popularity: 58.106,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/uqqJ243SqSYJxriAfBENNoNeOCO.jpg",
        genre_ids: [53, 27, 9648],
        original_language: "en",
        original_title: "Scream",
        poster_path: "/qvASAp0ZKkza023gjK1Tf2iiEos.jpg",
        video: false,
        vote_average: 8.4,
        vote_count: 5,
        overview:
          "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
        release_date: "2022-01-12",
        title: "Scream",
        id: 646385,
        popularity: 247.356,
        media_type: "movie",
      },
      {
        id: 639721,
        original_title: "The Addams Family 2",
        poster_path: "/ld7YB9vBRp1GM1DT3KmFWSmtBPB.jpg",
        video: false,
        vote_average: 7.3,
        overview:
          "The Addams get tangled up in more wacky adventures and find themselves involved in hilarious run-ins with all sorts of unsuspecting characters.",
        release_date: "2021-10-01",
        vote_count: 690,
        title: "The Addams Family 2",
        adult: false,
        backdrop_path: "/wfrfxivLOBtGMC98tIr2LSOeKSe.jpg",
        original_language: "en",
        genre_ids: [16, 12, 35, 10751],
        popularity: 548.093,
        media_type: "movie",
      },
      {
        original_title: "Halloween Kills",
        poster_path: "/qmJGd5IfURq8iPQ9KF3les47vFS.jpg",
        title: "Halloween Kills",
        video: false,
        vote_average: 6.9,
        overview:
          "Minutes after Laurie Strode, her daughter Karen and granddaughter Allyson left masked monster Michael Myers caged and burning in Laurie's basement, Laurie is rushed to the hospital with life-threatening injuries, believing she finally killed her lifelong tormentor. But when Michael manages to free himself from Laurie's trap, his ritual bloodbath resumes. As Laurie fights her pain and prepares to defend herself against him, she inspires all of Haddonfield to rise up against their unstoppable monster. The Strode women join a group of other survivors of Michael's first rampage who decide to take matters into their own hands, forming a vigilante mob that sets out to hunt Michael down, once and for all.",
        release_date: "2021-10-14",
        adult: false,
        id: 610253,
        vote_count: 1406,
        genre_ids: [27, 53],
        backdrop_path: "/fuuZFPc8x6gQ8mLGoBp9vrmcQMT.jpg",
        original_language: "en",
        popularity: 481.856,
        media_type: "movie",
      },
      {
        poster_path: "/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
        id: 566525,
        vote_average: 7.8,
        overview:
          "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
        release_date: "2021-09-01",
        title: "Shang-Chi and the Legend of the Ten Rings",
        adult: false,
        backdrop_path: "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
        vote_count: 5014,
        genre_ids: [28, 12, 14],
        video: false,
        original_language: "en",
        original_title: "Shang-Chi and the Legend of the Ten Rings",
        popularity: 2301.665,
        media_type: "movie",
      },
    ],
    total_pages: 1000,
    total_results: 20000,
  },
};
